### ISSUE TITLE
KDS-Modul Onkologie (2025)

### ISSUE THREAD

**Issue by karoline-buckow** [medizininformatik-initiative/kerndatensatz-meta#27]
### Phase 1: Einrichtung des Moduls

- [x] Erstellung Modulbeschreibung
- [x] Festlegung eines KDS-Teams
- [x] NSG-Beschluss zur Einrichtung des KDS-Moduls 

### Phase 2: Informationsmodellierung

- [x] Erstellung eines UML-Klassendiagramms
- [x] Erstellung einer Datensatzbeschreibung in ART-DECOR
- [x] inhaltliche Abstimmung des Informationsmodells
- [x] NSG-Beschluss zum Informationsmodell

### Phase 3: Technische Umsetzung

- [ ] FHIR Profilierung
- [ ] IG-Erstellung
- [ ] Erprobung durch Pilot-DIZ
- [ ] Erprobung der Abfragbarkeit durch das FDPG

### Phase 4: Ballotierung

- [ ] Ankündigung
- [ ] Aufnahme und Strukturierung der eingehenden Kommentare
- [ ] ggf. Infomationstermin während der Kommentierungsphase
- [ ] Auflösung der Kommtare
- [ ] Aktualisierung der Datensatzbeschreibung in ART-DECOR
- [ ] Aktualisierung des UML-Klassendiagramms
- [ ] NSG-Freigabe des Moduls
